### ISSUE TITLE
Allow CellBuilder to define cell width on construct

### ISSUE THREAD

**Issue by Prains** [sasha1107/excel-build#2]
Hello!

Thank you very much for this library. Excel-build makes creating excel files in javascript very easy.

Thing that i encountered when building excel files with this library, is that i cant define the default cell width when constructing cells. Right now i do thing like that: 

```
    data.forEach((item) => {
      sheet1.appendCustomRow(
        item.map((value) =>
          new CellBuilder(value)
            .setBorder({
              top: {
                style: "thin",
                color: { rgb: "rgb(0, 0, 0)" },
              },
              bottom: {
                style: "thin",
                color: { rgb: "rgb(0, 0, 0)" },
              },
              left: {
                style: "thin",
                color: { rgb: "rgb(0, 0, 0)" },
              },
              right: {
                style: "thin",
                color: { rgb: "rgb(0, 0, 0)" },
              },
            })
            .setAlignMentWrapText()
            .build()
        )
      );
    });
```

and would be happy to do something like that : 

```

    data.forEach((item) => {
      sheet1.appendCustomRow(
        item.map((value) =>
          new CellBuilder(value)
            .setBorder({
              top: {
                style: "thin",
                color: { rgb: "rgb(0, 0, 0)" },
              },
              bottom: {
                style: "thin",
                color: { rgb: "rgb(0, 0, 0)" },
              },
              left: {
                style: "thin",
                color: { rgb: "rgb(0, 0, 0)" },
              },
              right: {
                style: "thin",
                color: { rgb: "rgb(0, 0, 0)" },
              },
            })
            .width(50)
            .build()
        )
      );
    });
    ```
    
    is it possible to add feature like that?

**Comment by sasha1107** [comment]
Hello!!
I am grateful and happy that you are using the excel-build.
I'll confim and merge it.
Have a nice day!😄😄

네이버 메일앱에서 보냈습니다.
-----Original Message-----
보낸사람: ***@***.***>
받는사람: ***@***.***>
참조: ***@***.***>
날짜: 2024. 2. 16 오후 7:35:24
제목: [sasha1107/excel-build] Allow CellBuilder to define cell width on construct (Issue #2)

Hello!
Thank you very much for this library. Excel-build makes creating excel files in javascript very easy.
Thing that i encountered when building excel files with this library, is that i cant define the default cell width when constructing cells. Right now i do thing like that:
data.forEach((item) => { sheet1.appendCustomRow( item.map((value) => new CellBuilder(value) .setBorder({ top: { style: "thin", color: { rgb: "rgb(0, 0, 0)" }, }, bottom: { style: "thin", color: { rgb: "rgb(0, 0, 0)" }, }, left: { style: "thin", color: { rgb: "rgb(0, 0, 0)" }, }, right: { style: "thin", color: { rgb: "rgb(0, 0, 0)" }, }, }) .setAlignMentWrapText() .build() ) ); });
and would be happy to do something like that :
data.forEach((item) => { sheet1.appendCustomRow( item.map((value) => new CellBuilder(value) .setBorder({ top: { style: "thin", color: { rgb: "rgb(0, 0, 0)" }, }, bottom: { style: "thin", color: { rgb: "rgb(0, 0, 0)" }, }, left: { style: "thin", color: { rgb: "rgb(0, 0, 0)" }, }, right: { style: "thin", color: { rgb: "rgb(0, 0, 0)" }, }, }) .width(50) .build() ) ); }); ``` is it possible to add feature like that?

**Comment by sasha1107** [comment]
Hello!
Thank you for using excel-build :)
I will merge after checking it.
Have a nice day 😄😄
